repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: requirements-txt-fixer
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
