# Generated by Django 4.0.2 on 2022-02-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Concept name')),
                ('hint', models.JSONField(blank=True, verbose_name='Concept hint')),
                ('time_added', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Time Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Attrib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Attribute name')),
                ('datatype', models.JSONField(default='{"value_type": "str", "collection_type": null, "key_type": null}', verbose_name='Attribute data type')),
                ('time_added', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Time Updated')),
                ('of_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.concept')),
            ],
        ),
    ]
