# Generated by Django 4.0.2 on 2022-02-19 14:26

from django.db import migrations, models
import world.models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrib',
            name='metadata',
            field=models.JSONField(default=world.models.attrib_metadata_default, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='attrib',
            name='datatype',
            field=models.JSONField(default=world.models.attrib_datatype_default, verbose_name='Attribute data type'),
        ),
    ]
