# Generated by Django 4.0.2 on 2022-02-19 14:57

from django.db import migrations, models
import world.models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_attrib_metadata_alter_attrib_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrib',
            name='metadata',
            field=models.JSONField(blank=True, default=world.models.attrib_metadata_default, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='hint',
            field=models.JSONField(blank=True, default=world.models.concept_hint_default, verbose_name='Concept hint'),
        ),
    ]
