# Generated by Django 4.0.4 on 2022-05-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodtable',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
