# Generated by Django 4.0.4 on 2022-05-24 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_server_badtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('birthday', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='badtable',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_bad_table', to='server.badprofile'),
        ),
    ]
