# Generated by Django 4.0.4 on 2022-05-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_badprofile_badtable_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField(db_index=True, null=True)),
                ('total_earned', models.FloatField(null=True)),
                ('project_count', models.BigIntegerField(default=0)),
                ('project_not_complete_count', models.BigIntegerField(default=0)),
                ('ongoing_tickets', models.BigIntegerField(default=0)),
            ],
        ),
    ]
