# Generated by Django 4.0.4 on 2022-05-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_statsvendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsvendor',
            name='ongoing_tickets',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statsvendor',
            name='project_count',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statsvendor',
            name='project_not_complete_count',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
